export const intel14 = [
  {
    "model": "Core i9-14900KS",
    "release_year_initial": "2024 (Q1)",
    "p_cores": 8,
    "e_cores": 16,
    "total_threads": 32,
    "manufacturing_process_node": "Intel 7",
    "initial_price_usd_approx": 699,
    "socket": "LGA 1700",
    "base_power_tdp_w": 150,
    "max_turbo_power_w": 253, // Can exceed with specific motherboard settings/profiles
    "p_core_base_clock_ghz": 3.2,
    "p_core_boost_clock_ghz": 6.2,
    "e_core_base_clock_ghz": 2.4,
    "e_core_boost_clock_ghz": 4.5,
    "l2_cache_mb": 32,
    "l3_cache_mb": 36,
    "notes": "Special edition, highest clocks"
  },
  {
    "model": "Core i9-14900K",
    "release_year_initial": "2023 (Q4)",
    "p_cores": 8,
    "e_cores": 16,
    "total_threads": 32,
    "manufacturing_process_node": "Intel 7",
    "initial_price_usd_approx": 589,
    "socket": "LGA 1700",
    "base_power_tdp_w": 125,
    "max_turbo_power_w": 253,
    "p_core_base_clock_ghz": 3.2,
    "p_core_boost_clock_ghz": 6.0,
    "e_core_base_clock_ghz": 2.4,
    "e_core_boost_clock_ghz": 4.4,
    "l2_cache_mb": 32,
    "l3_cache_mb": 36,
    "notes": "Unlocked, with integrated graphics"
  },
  {
    "model": "Core i9-14900KF",
    "release_year_initial": "2023 (Q4)",
    "p_cores": 8,
    "e_cores": 16,
    "total_threads": 32,
    "manufacturing_process_node": "Intel 7",
    "initial_price_usd_approx": 564,
    "socket": "LGA 1700",
    "base_power_tdp_w": 125,
    "max_turbo_power_w": 253,
    "p_core_base_clock_ghz": 3.2,
    "p_core_boost_clock_ghz": 6.0,
    "e_core_base_clock_ghz": 2.4,
    "e_core_boost_clock_ghz": 4.4,
    "l2_cache_mb": 32,
    "l3_cache_mb": 36,
    "notes": "Unlocked, without integrated graphics"
  },
  {
    "model": "Core i9-14900",
    "release_year_initial": "2024 (Q1)",
    "p_cores": 8,
    "e_cores": 16,
    "total_threads": 32,
    "manufacturing_process_node": "Intel 7",
    "initial_price_usd_approx": 549,
    "socket": "LGA 1700",
    "base_power_tdp_w": 65,
    "max_turbo_power_w": 219,
    "p_core_base_clock_ghz": 2.0,
    "p_core_boost_clock_ghz": 5.8,
    "e_core_base_clock_ghz": 1.5,
    "e_core_boost_clock_ghz": 4.3,
    "l2_cache_mb": 32,
    "l3_cache_mb": 36,
    "notes": "Locked, with integrated graphics"
  },
  {
    "model": "Core i9-14900F",
    "release_year_initial": "2024 (Q1)",
    "p_cores": 8,
    "e_cores": 16,
    "total_threads": 32,
    "manufacturing_process_node": "Intel 7",
    "initial_price_usd_approx": 524,
    "socket": "LGA 1700",
    "base_power_tdp_w": 65,
    "max_turbo_power_w": 219,
    "p_core_base_clock_ghz": 2.0,
    "p_core_boost_clock_ghz": 5.8,
    "e_core_base_clock_ghz": 1.5,
    "e_core_boost_clock_ghz": 4.3,
    "l2_cache_mb": 32,
    "l3_cache_mb": 36,
    "notes": "Locked, without integrated graphics"
  },
  {
    "model": "Core i7-14700K",
    "release_year_initial": "2023 (Q4)",
    "p_cores": 8,
    "e_cores": 12,
    "total_threads": 28,
    "manufacturing_process_node": "Intel 7",
    "initial_price_usd_approx": 409,
    "socket": "LGA 1700",
    "base_power_tdp_w": 125,
    "max_turbo_power_w": 253,
    "p_core_base_clock_ghz": 3.4,
    "p_core_boost_clock_ghz": 5.6,
    "e_core_base_clock_ghz": 2.5,
    "e_core_boost_clock_ghz": 4.3,
    "l2_cache_mb": 28,
    "l3_cache_mb": 33,
    "notes": "Unlocked, with integrated graphics"
  },
  {
    "model": "Core i7-14700KF",
    "release_year_initial": "2023 (Q4)",
    "p_cores": 8,
    "e_cores": 12,
    "total_threads": 28,
    "manufacturing_process_node": "Intel 7",
    "initial_price_usd_approx": 384,
    "socket": "LGA 1700",
    "base_power_tdp_w": 125,
    "max_turbo_power_w": 253,
    "p_core_base_clock_ghz": 3.4,
    "p_core_boost_clock_ghz": 5.6,
    "e_core_base_clock_ghz": 2.5,
    "e_core_boost_clock_ghz": 4.3,
    "l2_cache_mb": 28,
    "l3_cache_mb": 33,
    "notes": "Unlocked, without integrated graphics"
  },
  {
    "model": "Core i7-14700",
    "release_year_initial": "2024 (Q1)",
    "p_cores": 8,
    "e_cores": 12,
    "total_threads": 28,
    "manufacturing_process_node": "Intel 7",
    "initial_price_usd_approx": 380, // User provided value, ARK RCP is $384
    "socket": "LGA 1700",
    "base_power_tdp_w": 65,
    "max_turbo_power_w": 219,
    "p_core_base_clock_ghz": 2.1,
    "p_core_boost_clock_ghz": 5.4,
    "e_core_base_clock_ghz": 1.5,
    "e_core_boost_clock_ghz": 4.2,
    "l2_cache_mb": 28,
    "l3_cache_mb": 33,
    "notes": "Locked, with integrated graphics"
  },
  {
    "model": "Core i7-14700F",
    "release_year_initial": "2024 (Q1)",
    "p_cores": 8,
    "e_cores": 12,
    "total_threads": 28,
    "manufacturing_process_node": "Intel 7",
    "initial_price_usd_approx": 355, // User provided value, ARK RCP is $359
    "socket": "LGA 1700",
    "base_power_tdp_w": 65,
    "max_turbo_power_w": 219,
    "p_core_base_clock_ghz": 2.1,
    "p_core_boost_clock_ghz": 5.4,
    "e_core_base_clock_ghz": 1.5,
    "e_core_boost_clock_ghz": 4.2,
    "l2_cache_mb": 28,
    "l3_cache_mb": 33,
    "notes": "Locked, without integrated graphics"
  },
  {
    "model": "Core i5-14600K",
    "release_year_initial": "2023 (Q4)",
    "p_cores": 6,
    "e_cores": 8,
    "total_threads": 20,
    "manufacturing_process_node": "Intel 7",
    "initial_price_usd_approx": 319,
    "socket": "LGA 1700",
    "base_power_tdp_w": 125,
    "max_turbo_power_w": 181,
    "p_core_base_clock_ghz": 3.5,
    "p_core_boost_clock_ghz": 5.3,
    "e_core_base_clock_ghz": 2.6,
    "e_core_boost_clock_ghz": 4.0,
    "l2_cache_mb": 20,
    "l3_cache_mb": 24,
    "notes": "Unlocked, with integrated graphics"
  },
  {
    "model": "Core i5-14600KF",
    "release_year_initial": "2023 (Q4)",
    "p_cores": 6,
    "e_cores": 8,
    "total_threads": 20,
    "manufacturing_process_node": "Intel 7",
    "initial_price_usd_approx": 294,
    "socket": "LGA 1700",
    "base_power_tdp_w": 125,
    "max_turbo_power_w": 181,
    "p_core_base_clock_ghz": 3.5,
    "p_core_boost_clock_ghz": 5.3,
    "e_core_base_clock_ghz": 2.6,
    "e_core_boost_clock_ghz": 4.0,
    "l2_cache_mb": 20,
    "l3_cache_mb": 24,
    "notes": "Unlocked, without integrated graphics"
  },
  {
    "model": "Core i5-14500",
    "release_year_initial": "2024 (Q1)",
    "p_cores": 6,
    "e_cores": 8,
    "total_threads": 20,
    "manufacturing_process_node": "Intel 7", // May use Alder Lake die with Raptor Lake L3 config
    "initial_price_usd_approx": 232,
    "socket": "LGA 1700",
    "base_power_tdp_w": 65,
    "max_turbo_power_w": 154,
    "p_core_base_clock_ghz": 2.6,
    "p_core_boost_clock_ghz": 5.0,
    "e_core_base_clock_ghz": 1.9,
    "e_core_boost_clock_ghz": 3.7,
    "l2_cache_mb": 11.5, // (6 * 1.25MB P-core) + (2 * 2MB E-core cluster)
    "l3_cache_mb": 24,
    "notes": "Locked, with integrated graphics"
  },
  {
    "model": "Core i5-14400",
    "release_year_initial": "2024 (Q1)",
    "p_cores": 6,
    "e_cores": 4,
    "total_threads": 16,
    "manufacturing_process_node": "Intel 7", // May use Alder Lake die
    "initial_price_usd_approx": 221,
    "socket": "LGA 1700",
    "base_power_tdp_w": 65,
    "max_turbo_power_w": 148,
    "p_core_base_clock_ghz": 2.5,
    "p_core_boost_clock_ghz": 4.7,
    "e_core_base_clock_ghz": 1.8,
    "e_core_boost_clock_ghz": 3.5,
    "l2_cache_mb": 9.5, // (6 * 1.25MB P-core) + (1 * 2MB E-core cluster)
    "l3_cache_mb": 20,
    "notes": "Locked, with integrated graphics"
  },
  {
    "model": "Core i5-14400F",
    "release_year_initial": "2024 (Q1)",
    "p_cores": 6,
    "e_cores": 4,
    "total_threads": 16,
    "manufacturing_process_node": "Intel 7", // May use Alder Lake die
    "initial_price_usd_approx": 196,
    "socket": "LGA 1700",
    "base_power_tdp_w": 65,
    "max_turbo_power_w": 148,
    "p_core_base_clock_ghz": 2.5,
    "p_core_boost_clock_ghz": 4.7,
    "e_core_base_clock_ghz": 1.8,
    "e_core_boost_clock_ghz": 3.5,
    "l2_cache_mb": 9.5,
    "l3_cache_mb": 20,
    "notes": "Locked, without integrated graphics"
  },
  {
    "model": "Core i3-14100",
    "release_year_initial": "2024 (Q1)",
    "p_cores": 4,
    "e_cores": 0,
    "total_threads": 8,
    "manufacturing_process_node": "Intel 7", // Alder Lake die
    "initial_price_usd_approx": 132,
    "socket": "LGA 1700",
    "base_power_tdp_w": 60,
    "max_turbo_power_w": 110,
    "p_core_base_clock_ghz": 3.5,
    "p_core_boost_clock_ghz": 4.7,
    "e_core_base_clock_ghz": 0,
    "e_core_boost_clock_ghz": 0,
    "l2_cache_mb": 5, // (4 * 1.25MB P-core)
    "l3_cache_mb": 12,
    "notes": "Locked, with integrated graphics"
  },
  {
    "model": "Core i3-14100F",
    "release_year_initial": "2024 (Q1)",
    "p_cores": 4,
    "e_cores": 0,
    "total_threads": 8,
    "manufacturing_process_node": "Intel 7", // Alder Lake die
    "initial_price_usd_approx": 107,
    "socket": "LGA 1700",
    "base_power_tdp_w": 58,
    "max_turbo_power_w": 110,
    "p_core_base_clock_ghz": 3.5,
    "p_core_boost_clock_ghz": 4.7,
    "e_core_base_clock_ghz": 0,
    "e_core_boost_clock_ghz": 0,
    "l2_cache_mb": 5,
    "l3_cache_mb": 12,
    "notes": "Locked, without integrated graphics"
  }
];

export const intel13 = [
  {
    "model": "Core i9-13900K",
    "release_year_initial": "2022 (Q4)",
    "p_cores": 8,
    "e_cores": 16,
    "total_threads": 32,
    "manufacturing_process_node": "Intel 7",
    "initial_price_usd_approx": 589,
    "socket": "LGA 1700",
    "base_power_tdp_w": 125,
    "max_turbo_power_w": 253,
    "p_core_base_clock_ghz": 3.0,
    "p_core_boost_clock_ghz": 5.8,
    "e_core_base_clock_ghz": 2.2,
    "e_core_boost_clock_ghz": 4.3,
    "l2_cache_mb": 32,
    "l3_cache_mb": 36,
    "notes": "Unlocked, with integrated graphics"
  },
  {
    "model": "Core i9-13900KF",
    "release_year_initial": "2022 (Q4)",
    "p_cores": 8,
    "e_cores": 16,
    "total_threads": 32,
    "manufacturing_process_node": "Intel 7",
    "initial_price_usd_approx": 564,
    "socket": "LGA 1700",
    "base_power_tdp_w": 125,
    "max_turbo_power_w": 253,
    "p_core_base_clock_ghz": 3.0,
    "p_core_boost_clock_ghz": 5.8,
    "e_core_base_clock_ghz": 2.2,
    "e_core_boost_clock_ghz": 4.3,
    "l2_cache_mb": 32,
    "l3_cache_mb": 36,
    "notes": "Unlocked, without integrated graphics"
  },
  {
    "model": "Core i9-13900",
    "release_year_initial": "2023 (Q1)",
    "p_cores": 8,
    "e_cores": 16,
    "total_threads": 32,
    "manufacturing_process_node": "Intel 7",
    "initial_price_usd_approx": 549,
    "socket": "LGA 1700",
    "base_power_tdp_w": 65,
    "max_turbo_power_w": 219,
    "p_core_base_clock_ghz": 2.0,
    "p_core_boost_clock_ghz": 5.6,
    "e_core_base_clock_ghz": 1.5,
    "e_core_boost_clock_ghz": 4.2,
    "l2_cache_mb": 32,
    "l3_cache_mb": 36,
    "notes": "Locked, with integrated graphics"
  },
  {
    "model": "Core i9-13900F",
    "release_year_initial": "2023 (Q1)",
    "p_cores": 8,
    "e_cores": 16,
    "total_threads": 32,
    "manufacturing_process_node": "Intel 7",
    "initial_price_usd_approx": 524,
    "socket": "LGA 1700",
    "base_power_tdp_w": 65,
    "max_turbo_power_w": 219,
    "p_core_base_clock_ghz": 2.0,
    "p_core_boost_clock_ghz": 5.6,
    "e_core_base_clock_ghz": 1.5,
    "e_core_boost_clock_ghz": 4.2,
    "l2_cache_mb": 32,
    "l3_cache_mb": 36,
    "notes": "Locked, without integrated graphics"
  },
  {
    "model": "Core i7-13700K",
    "release_year_initial": "2022 (Q4)",
    "p_cores": 8,
    "e_cores": 8,
    "total_threads": 24,
    "manufacturing_process_node": "Intel 7",
    "initial_price_usd_approx": 409,
    "socket": "LGA 1700",
    "base_power_tdp_w": 125,
    "max_turbo_power_w": 253,
    "p_core_base_clock_ghz": 3.4,
    "p_core_boost_clock_ghz": 5.4,
    "e_core_base_clock_ghz": 2.5,
    "e_core_boost_clock_ghz": 4.2,
    "l2_cache_mb": 24,
    "l3_cache_mb": 30,
    "notes": "Unlocked, with integrated graphics"
  },
  {
    "model": "Core i7-13700KF",
    "release_year_initial": "2022 (Q4)",
    "p_cores": 8,
    "e_cores": 8,
    "total_threads": 24,
    "manufacturing_process_node": "Intel 7",
    "initial_price_usd_approx": 384,
    "socket": "LGA 1700",
    "base_power_tdp_w": 125,
    "max_turbo_power_w": 253,
    "p_core_base_clock_ghz": 3.4,
    "p_core_boost_clock_ghz": 5.4,
    "e_core_base_clock_ghz": 2.5,
    "e_core_boost_clock_ghz": 4.2,
    "l2_cache_mb": 24,
    "l3_cache_mb": 30,
    "notes": "Unlocked, without integrated graphics"
  },
  {
    "model": "Core i7-13700",
    "release_year_initial": "2023 (Q1)",
    "p_cores": 8,
    "e_cores": 8,
    "total_threads": 24,
    "manufacturing_process_node": "Intel 7",
    "initial_price_usd_approx": 380, // User provided value, ARK RCP is $384
    "socket": "LGA 1700",
    "base_power_tdp_w": 65,
    "max_turbo_power_w": 219,
    "p_core_base_clock_ghz": 2.1,
    "p_core_boost_clock_ghz": 5.2,
    "e_core_base_clock_ghz": 1.5,
    "e_core_boost_clock_ghz": 4.1,
    "l2_cache_mb": 24,
    "l3_cache_mb": 30,
    "notes": "Locked, with integrated graphics"
  },
  {
    "model": "Core i7-13700F",
    "release_year_initial": "2023 (Q1)",
    "p_cores": 8,
    "e_cores": 8,
    "total_threads": 24,
    "manufacturing_process_node": "Intel 7",
    "initial_price_usd_approx": 355, // User provided value, ARK RCP is $359
    "socket": "LGA 1700",
    "base_power_tdp_w": 65,
    "max_turbo_power_w": 219,
    "p_core_base_clock_ghz": 2.1,
    "p_core_boost_clock_ghz": 5.2,
    "e_core_base_clock_ghz": 1.5,
    "e_core_boost_clock_ghz": 4.1,
    "l2_cache_mb": 24,
    "l3_cache_mb": 30,
    "notes": "Locked, without integrated graphics"
  },
  {
    "model": "Core i5-13600K",
    "release_year_initial": "2022 (Q4)",
    "p_cores": 6,
    "e_cores": 8,
    "total_threads": 20,
    "manufacturing_process_node": "Intel 7",
    "initial_price_usd_approx": 319,
    "socket": "LGA 1700",
    "base_power_tdp_w": 125,
    "max_turbo_power_w": 181,
    "p_core_base_clock_ghz": 3.5,
    "p_core_boost_clock_ghz": 5.1,
    "e_core_base_clock_ghz": 2.6,
    "e_core_boost_clock_ghz": 3.9,
    "l2_cache_mb": 20,
    "l3_cache_mb": 24,
    "notes": "Unlocked, with integrated graphics"
  },
  {
    "model": "Core i5-13600KF",
    "release_year_initial": "2022 (Q4)",
    "p_cores": 6,
    "e_cores": 8,
    "total_threads": 20,
    "manufacturing_process_node": "Intel 7",
    "initial_price_usd_approx": 294,
    "socket": "LGA 1700",
    "base_power_tdp_w": 125,
    "max_turbo_power_w": 181,
    "p_core_base_clock_ghz": 3.5,
    "p_core_boost_clock_ghz": 5.1,
    "e_core_base_clock_ghz": 2.6,
    "e_core_boost_clock_ghz": 3.9,
    "l2_cache_mb": 20,
    "l3_cache_mb": 24,
    "notes": "Unlocked, without integrated graphics"
  },
  {
    "model": "Core i5-13500",
    "release_year_initial": "2023 (Q1)",
    "p_cores": 6,
    "e_cores": 8,
    "total_threads": 20,
    "manufacturing_process_node": "Intel 7", // May use Alder Lake die with Raptor Lake L3 config
    "initial_price_usd_approx": 242,
    "socket": "LGA 1700",
    "base_power_tdp_w": 65,
    "max_turbo_power_w": 154,
    "p_core_base_clock_ghz": 2.5,
    "p_core_boost_clock_ghz": 4.8,
    "e_core_base_clock_ghz": 1.8,
    "e_core_boost_clock_ghz": 3.5,
    "l2_cache_mb": 11.5, // (6 * 1.25MB P-core) + (2 * 2MB E-core cluster)
    "l3_cache_mb": 24,
    "notes": "Locked, with integrated graphics"
  },
  {
    "model": "Core i5-13400",
    "release_year_initial": "2023 (Q1)",
    "p_cores": 6,
    "e_cores": 4,
    "total_threads": 16,
    "manufacturing_process_node": "Intel 7", // May use Alder Lake die
    "initial_price_usd_approx": 221,
    "socket": "LGA 1700",
    "base_power_tdp_w": 65,
    "max_turbo_power_w": 148,
    "p_core_base_clock_ghz": 2.5,
    "p_core_boost_clock_ghz": 4.6,
    "e_core_base_clock_ghz": 1.8,
    "e_core_boost_clock_ghz": 3.3,
    "l2_cache_mb": 9.5, // (6 * 1.25MB P-core) + (1 * 2MB E-core cluster)
    "l3_cache_mb": 20,
    "notes": "Locked, with integrated graphics"
  },
  {
    "model": "Core i5-13400F",
    "release_year_initial": "2023 (Q1)",
    "p_cores": 6,
    "e_cores": 4,
    "total_threads": 16,
    "manufacturing_process_node": "Intel 7", // May use Alder Lake die
    "initial_price_usd_approx": 196,
    "socket": "LGA 1700",
    "base_power_tdp_w": 65,
    "max_turbo_power_w": 148,
    "p_core_base_clock_ghz": 2.5,
    "p_core_boost_clock_ghz": 4.6,
    "e_core_base_clock_ghz": 1.8,
    "e_core_boost_clock_ghz": 3.3,
    "l2_cache_mb": 9.5,
    "l3_cache_mb": 20,
    "notes": "Locked, without integrated graphics"
  },
  {
    "model": "Core i3-13100",
    "release_year_initial": "2023 (Q1)",
    "p_cores": 4,
    "e_cores": 0,
    "total_threads": 8,
    "manufacturing_process_node": "Intel 7", // Alder Lake die
    "initial_price_usd_approx": 132,
    "socket": "LGA 1700",
    "base_power_tdp_w": 60,
    "max_turbo_power_w": 89,
    "p_core_base_clock_ghz": 3.4,
    "p_core_boost_clock_ghz": 4.5,
    "e_core_base_clock_ghz": 0,
    "e_core_boost_clock_ghz": 0,
    "l2_cache_mb": 5, // (4 * 1.25MB P-core)
    "l3_cache_mb": 12,
    "notes": "Locked, with integrated graphics"
  },
  {
    "model": "Core i3-13100F",
    "release_year_initial": "2023 (Q1)",
    "p_cores": 4,
    "e_cores": 0,
    "total_threads": 8,
    "manufacturing_process_node": "Intel 7", // Alder Lake die
    "initial_price_usd_approx": 107,
    "socket": "LGA 1700",
    "base_power_tdp_w": 58,
    "max_turbo_power_w": 89,
    "p_core_base_clock_ghz": 3.4,
    "p_core_boost_clock_ghz": 4.5,
    "e_core_base_clock_ghz": 0,
    "e_core_boost_clock_ghz": 0,
    "l2_cache_mb": 5,
    "l3_cache_mb": 12,
    "notes": "Locked, without integrated graphics"
  }
];